pip install eclipse-sumo
pip install traci
pip install libsumo
pip install sumo-rl
pip install gymnasium
pip install pettingzoo
pip install torch_geometric
pip install transformers
pip install torch-scatter